name: Build SimpleTalk (Linux .deb & Windows .exe)

on:
  push:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR with Maven
        run: mvn -B clean package --file pom.xml

      - name: Package app for Linux (.deb)
        run: |
          mkdir input
          cp target/*-SNAPSHOT.jar input/app.jar
          jpackage \
            --input input \
            --name SimpleTalk \
            --main-jar app.jar \
            --main-class com.example.websocket_project.client.App \
            --type deb \
            --app-version 1.0.0 \
            --vendor "Hemra Ashyrov Pvt." \
            --dest out

      - name: Upload Linux artifact (.deb)
        uses: actions/upload-artifact@v3
        with:
          name: linux-deb
          path: out/*

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR with Maven
        run: mvn -B clean package --file pom.xml

      - name: Package app for Windows (.exe)
        run: |
          mkdir input
          copy target\*-SNAPSHOT.jar input\app.jar
          jpackage ^
            --input input ^
            --name SimpleTalk ^
            --main-jar app.jar ^
            --main-class com.example.websocket_project.client.App ^
            --type exe ^
            --app-version 1.0.0 ^
            --vendor "Hemra Ashyrov Pvt." ^
            --icon icon.ico ^
            --dest out

      - name: Upload Windows artifact (.exe)
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: out/*
